# docker-compose.yml
version: '3.8'
services:
  app:
    build:
      context: .
    container_name: agroforestry_vis_app
    depends_on:
      - database
    command: "rails s -p 3000 -b 0.0.0.0"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    env_file: .env.development
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      RAILS_ENV: development

  database:
    image: postgres:14-alpine
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  bundle_cache: