# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:14-alpine
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: agroforestry_vis_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/app_development
      RAILS_ENV: development
    depends_on:
      - db

volumes:
  postgres_data:
  bundle_cache: