# The default section defines the common settings for all environments (dev, test, prod).
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

# Specific settings to the development env.
development:
  <<: *default
  database: app_development

# Specific settings to the test env.
test:
  <<: *default
  database: app_test

# Specific settings to the prod env.
production:
  <<: *default
  database: app_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>