# The default section defines the common settings for all environments (dev, test, prod).
default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  host: <%= ENV['DATABASE_HOST'] %>

# Specific settings to the development env.
development:
  <<: *default
  pool: <%= ENV['RAILS_MAX_THREADS'] { 5 } %>

# Specific settings to the prod env.
production:
  <<: *default
  pool: <%= ENV['RAILS_MAX_THREADS'] { 5 } %>

# Specific settings to the test env.
test:
  <<: *default
  database: <%= ENV['DATABASE_TEST_NAME'] %>